repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]

  # Pylint: only run on pre-commit (read-only check)
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        stages: [pre-commit]
        require_serial: true
        always_run: false
        args:
          - "--rcfile=.pylintrc"
          - "--reports=no"
          - "--score=no"
          - "--output-format=text"
