repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.23
    hooks:
    - id: uv-sync
      stages: [pre-commit]
      args: ["--locked", "--all-packages"] # if this fails, run 'uv lock' to regenerate exact dependency versions from pyproject.toml

  # Pylint: only run on pre-commit (read-only check)
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        stages: [pre-commit]
        require_serial: true
        pass_filenames: true
        always_run: false
        args:
          - "--rcfile=.pylintrc"
          - "--reports=no"
          - "--score=no"
