repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.7
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc, --reports=no, --score=no]
        additional_dependencies: [pylint-django, pylint-celery]