[project]
name = "arch-reconstruct-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepagents>=0.0.5",
    "langchain>=0.3.27",
    "pylint>=3.3.9",
]
